server:
  port: 8000
  
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio-service?useTimezone=true&serverTimezone=UTC
    username: root
    password: Mudar@1234
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio-service
    user: root
    password: Mudar@1234
