server:
  port: 8888

spring:
  application:
    name: igor-config-server
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IgorCastro-dev/igor-config-server
          search-paths:
          - 'greeting-service*'
